version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    - gocyclo
    - revive
    - misspell
    - nakedret
    - gosec
    - dupl
    - gocritic
    - funlen
    - lll
    - nestif
    - godot
    - unconvert
    - unparam
    - goconst
    - goimports

formatters:
  enable:
    - gofmt
    - goimports
