version: "2"

run:
  timeout: 5m

linters:
  exclusions:
    rules:
      - path: /
        linters:
        - typecheck
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    - gocyclo
    - revive
    - misspell
    - nakedret
    - gosec
    - dupl
    - gocritic
    - funlen
    - lll
    - nestif
    - godot
    - unconvert
    - unparam
    - goconst

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
